Class {
	#name : #'Topografía',
	#superclass : #Object,
	#category : #'Topografia-OO2-model'
}

{ #category : #'as yet unclassified' }
Topografía >> desperdicio [
	self subclassResponsibility 
]

{ #category : #comparing }
Topografía >> equals: aTopography [
	self subclassResponsibility 
	
]

{ #category : #testing }
Topografía >> isPorcion [
	self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
Topografía >> porcionDeAgua [
	self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
Topografía >> terrenoProductivo [
	self subclassResponsibility 
]
